= Rediscogs
RediSearch demo based on data from https://data.discogs.com[discogs.com].

== Setup

This demo requires Java 8, https://oss.redislabs.com/redisearch/Quick_Start/[Redisearch] and https://www.npmjs.com[npm]

If you would like to see album covers you will also need to register at Discogs.com and https://www.discogs.com/settings/developers[generate an API token]

== Running the demo

=== RediSearch
To run a RediSearch instance using docker:
[source,sh]
----
docker run -p 6379:6379 redislabs/redisearch:latest
----

=== Server
Clone and build JRediSearch 0.12:
[source,sh]
----
git clone https://github.com/RedisLabs/JRediSearch.git
cd JRediSearch
mvn clean install -DskipTests
----

Clone this git repository and build it:
[source,sh]
----
git clone https://github.com/Redislabs-Solution-Architects/rediscogs.git
cd rediscogs
mvn clean install
----

=== Running locally
Run the application:
[source,sh]
----
java -jar server/target/rediscogs-server-0.0.1-SNAPSHOT.jar --discogs-api-token=<your_discogs_token> --spring.redis.host=<host> --spring.redis.port=<port>
----

=== Running in Docker
Build the Docker image:
[source,sh]
----
cd server
mvn dockerfile:build
----
Run the container:
[source,sh]
----
docker run  -e "spring.redis.host=docker.for.mac.localhost" -e "discogs-api-token=<your_discogs_token>" -p 8080:8080 redislabs/rediscogs
----

=== Deploying to Cloud Foundry
. Create a Redis service instance named `rediscogs_redis` with Apps Manager or `cf create-service`
. Push the application
+
[source,sh]
----
cf push
----

== Configuration

.Available configuration properties
|===
|Property |Description |Default

|`spring.redis.host`
|Redis database host name
|`localhost`

|`spring.redis.port`
|Redis database port
|`6379`

|`spring.cache.cache-names`
|Caches to be created on startup
|`images`

|`spring.cache.redis.time-to-live`
|duration in milliseconds
|`600000`

|`skip-load`
|skip loading of Discogs masters file
|`false`

|`batch-size`
|number of elements per batch processing
|`50`

|`masters-file`
|Discogs Masters database file location
|https://discogs-data.s3-us-west-2.amazonaws.com/data/2018/discogs_20180801_masters.xml.gz[discogs_20180801]

|`masters-index`
|name of RediSearch index for masters
|`mastersIdx`

|`artists-suggestion-index`
|name of RediSearch suggestion index for artists
|`artistsSuggestionIdx`

|`discogs-api-url`
|URL for Discogs API masters endpoint
|`https://api.discogs.com/masters/{id}`

|`discogs-api-token`
|Your Discogs API token
|`wI...qz`

|`discogs-api-delay`
|Duration in milliseconds to sleep before Discogs API call (useful to demonstrate  caching)
|`100`

|`discogs-api-user-agent`
|User agent to use for Discogs API calls
|`com.redislabs.rediscogs.useragent`

|`redisearch-host`
|RediSearch database hostname
|`localhost`

|`redisearch-port`
|RediSearch database port
|`6379`

|`search-results-limit`
|Maximum number of results for searches (`LIMIT` argument in `FT.SEARCH`)
|`20`
|===

== Demo Steps
=== Redis CLI
. Show number of keys in Redis: `info`
. Run simple keyword search: `FT.SEARCH mastersIdx spring`
. Show Hash for one of the previous matches: `HGETALL "master:834798"`
. Highlight the `_class` field that Spring Data Redis uses to keep track of the original class (for object deserialization purposes)
. Run prefix search: `FT.SEARCH mastersIdx spring*`
. Show Hash for one of the previous matches: `HGETALL "master:151353"`

=== Web UI
. Open http://localhost:8080
. Enter some characters in the Artist field to retrieve suggestions from RediSearch (e.g. `Dusty`)
. Select an artist from the autocompleted options and click on the `Submit` button
. Notice how long it takes to load images from the https://api.discogs.com[Discogs API]
. After all images have been loaded, click on the `Submit` button again
. Notice how fast the images are loading this time around
. In `redis-cli` show cached images: `KEYS "images::*"`
. Show type of a cached image: `TYPE "images::319832"`
. Display image bytes stored in String data structure: `GET "images::319832"`
. Go back to Web UI and select a different artist (e.g. `Bruce Springsteen`)
. Hit the `Submit` button
. Refine the search by adding a numeric filter on release year in `Query` field: `@year:[1980 1990]`
. Refine the search further by adding a filter on release genre: `@year:[1980 1990] @genres:pop`