= Rediscogs
:source-highlighter: coderay
:icons: font


RediSearch demo based on data from https://data.discogs.com[discogs.com].

== Setup

=== Requirements
This demo requires Java 8 or higher, https://oss.redislabs.com/redisearch/Quick_Start/[Redisearch] and https://www.npmjs.com[npm]

If you would like to see album covers you will also need to register at Discogs.com and https://www.discogs.com/settings/developers[generate an API token]

=== RediSearch
You will need a RediSearch database to run the demo. To run a RediSearch using Docker:
[source,shell]
----
$ docker run -p 6379:6379 redislabs/redisearch:latest
----

== Running the demo
Clone this git repository and build it:
[source,shell]
----
$ git clone https://github.com/Redislabs-Solution-Architects/rediscogs.git
$ cd rediscogs
$ ./mvnw clean install
----

=== Running locally
Run the application:
[source,shell]
----
$ java -jar server/target/rediscogs-server-1.2.0.jar --discogs.api.token=<your_discogs_token> --spring.redis.host=<host> --spring.redis.port=<port>
----

=== Running in Docker
Build the Docker image:
[source,shell]
----
$ cd server
$ mvn dockerfile:build
----

Run the container:
[source,shell]
----
$ docker run  -e "spring.redis.host=docker.for.mac.localhost" -e "discogs.api.token=<your_discogs_token>" -p 8080:8080 redislabs/rediscogs
----

=== Deploying to Cloud Foundry
. Create a Redis service instance named `rediscogs_redis` with Apps Manager or `cf create-service`
. Push the application
[source,shell]
----
$ cf push
----

== Configuration

.Available configuration properties
|===
|Property |Description

|`spring.redis.host`
|Redis database hostname

|`spring.redis.port`
|Redis database port

|`image-delay`
|Duration in milliseconds to sleep before getting an image from Discogs API (useful to demonstrate  caching)

|`search-results-limit`
|Maximum number of results for searches (`LIMIT` argument in `FT.SEARCH`)

|`spring.cache.cache-names`
|Caches to be created on startup

|`spring.cache.redis.time-to-live`
|duration in milliseconds

|`spring.redisearch.host`
|RediSearch database hostname

|`spring.redisearch.port`
|RediSearch database port

|`discogs.data.master-index`
|Name of the master index

|`discogs.data.artist-suggestion-index`
|Name of the artist suggestion index

|`discogs.data.url`
|Discogs Masters database URI template

|`discogs.data.batch-size`
|number of elements per batch processing

|`discogs.data.skip`
|skip loading of Discogs data file

|`discogs.data.no-op`
|Disables all writes to Redis (only reads the data file). Useful for performance testing

|`discogs.api.url`
|URL for Discogs API masters endpoint

|`discogs.api.token`
|Your Discogs API token

|`discogs.api.user-agent`
|User agent to use for Discogs API calls

|`spring.task.execution.pool.core-size`
|Number of threads to use for data loading jobs

|`spring.redis.jedis.pool.max-active`
|Maximum number of connections that can be allocated by the Jedis pool
|===

== Data Model

=== Master
Each master release (i.e. album) is stored as a RediSearch document under the `masters` index with the following fields:
|===
|Field Name|Type

|artist
|Text

|artistId
|Tag

|genres
|Tag

|title
|Text + Phonetic

|year
|Numeric
|===

== Demo Steps

=== Searching with redis-cli
. Launch `redis-cli`
. Show number of documents in RediSearch index:
+
`FT.INFO masters`
. Run simple keyword search:
+
`FT.SEARCH masters java`
+
NOTE: `title` is a phonetic text field so you will notice documents with different spellings in that field
. Run prefix search:
+
`FT.SEARCH masters spring*`

=== Search
. Open http://localhost:8080
. Enter some characters in the Artist field to retrieve suggestions from RediSearch (e.g. `Dusty`)
. Select an artist from the auto-complete options and click on the `Submit` button
. Refine the search by adding a numeric filter on release year in `Query` field:
+
`@year:[1960 1970]`
. Refine the search further by adding a filter on release genres:
+
`@year:[1960 1970] @genres:{pop | rock}`

=== Cache
. Select a different artist and hit `Submit`
. Notice how long it takes to load images from the https://api.discogs.com[Discogs API]
. After all images have been loaded, click on the `Submit` button again
. Notice how fast the images are loading this time around
. In `redis-cli` show cached images:
+
`KEYS "images::*"`
. Show type of a cached image:
+
`TYPE "images::319832"`
. Display image bytes stored in String data structure:
+
`GET "images::319832"`

=== Session Store
. Enter your name in the top right section of the page 
. Choose an artist and hit `Submit`
. Click `like` on some of the returned albums
. Hit `Submit` again to refresh the list of albums
. Notice how your likes are kept in the current session
. In `redis-cli` show session-related keys:
+
`KEYS "spring:session:*"`
. Choose a session entry and show its content:
+
`HGETALL "spring:session:sessions:d1e08957-6cee-49b6-81af-b21720d3c372"`

=== Streams
. Open http://localhost:8080/#/likes in another browser window, side-by-side with the previous one 
. In the search page click `like` on any album. Notice the likes showing up in real-time in the other browser window
. In a terminal window listen for messages on the stream:
[source,shell]
----
$ while true; do redis-cli XREAD BLOCK 0 STREAMS likes:stream $; done
...
1) 1) "1557201909758-0"
   2)  1) "artist"
       2) "Herbie Hancock"
       3) "year"
       4) "1962"
       5) "genres"
       6) "Jazz,Bop"
       7) "artistId"
       8) "3865"
       9) "id"
      10) "163780"
      11) "title"
      12) "Takin' Off"
      13) "username"
      14) "Julien"
----
